# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JSConf Budapest 2017
email: info@jsconfbp.com
description: > # this means to ignore newlines until "baseurl:"
  JSConf Budapest is a JSConf family member 2-day non-profit
  for-the-community by-the-community conference about JavaScript
  in Budapest, Hungary.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://jsconfbp.com # the base hostname & protocol for your site, e.g. http://example.com
keywords: jsconf, javascript, jsconfbp, conference, budapest, jsconf budapest
twitter_username: jsconfbp
github_username:  jsconfbp

collections:
  updates:
    output: true
    permalink: /:collection/:name/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
sass:
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
